// Generated by CoffeeScript 1.10.0
(function() {
  var ConsoleLogger, GenericEmitter, LOGLEVEL, Logger, MessageEmitter, Toolbox;

  Toolbox = Observatory.Toolbox, MessageEmitter = Observatory.MessageEmitter, GenericEmitter = Observatory.GenericEmitter, Logger = Observatory.Logger, ConsoleLogger = Observatory.ConsoleLogger, LOGLEVEL = Observatory.LOGLEVEL;

  describe('Toolbox - main set of tools and the only class a user may generally need to use', function() {
    return it('Should work', function() {
      var f, ret, tb, tt;
      tb = new Toolbox;
      tb.info("Toolbox created");
      tb.exec(function() {
        var b, i, j, results;
        results = [];
        for (i = j = 1; j <= 500000; i = ++j) {
          results.push(b = i * i);
        }
        return results;
      });
      f = function(max) {
        var b, i, j, ref;
        for (i = j = 1, ref = max; 1 <= ref ? j <= ref : j >= ref; i = 1 <= ref ? ++j : --j) {
          if (i > 573000) {
            throw new Error("Test error out of the wrapped function!");
          }
          b = i * i;
        }
        return b;
      };
      ret = tb.exec(function() {
        return f(1500000);
      });
      tt = _.wrap(f, tb.exec);
      console.log("Do we see ret? " + ret);
      return tt();
    });
  });

}).call(this);
