// Generated by CoffeeScript 1.6.3
(function() {
  require('underscore');

  Observatory.MessageEmitter = (function() {
    MessageEmitter._loggers = [];

    MessageEmitter.prototype._getLoggers = function() {
      return this._loggers;
    };

    function MessageEmitter(name) {
      this.name = name;
      this._loggers = [];
    }

    MessageEmitter.prototype.subscribeLogger = function(logger) {
      return this._loggers.push(logger);
    };

    MessageEmitter.prototype.unsubscribeLogger = function(logger) {
      return this._loggers = _.without(this._loggers, [logger]);
    };

    MessageEmitter.prototype.emitMessage = function(message) {
      var l, _i, _len, _ref, _results;
      _ref = this._loggers;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        l = _ref[_i];
        _results.push(l.addMessage(message));
      }
      return _results;
    };

    return MessageEmitter;

  })();

  (typeof exports !== "undefined" && exports !== null ? exports : this).Observatory.MessageEmitter = Observatory.MessageEmitter;

}).call(this);
